### ISSUE TITLE
Fail on start if there is no conf file available

### ISSUE THREAD

**Issue by ewelinawilkosz2** [Praqma/configuration-as-code-plugin#11]
currently configuration file has to be put in conf directory manually and if it's not there Jenkins fails on start - it shouldn't fail with incomprehensible stacktrace but provide a nice message instead
maybe even command how to copy template file into the right directory?

**Comment by groenborg** [comment]
We already check if the file exists, so it should be easy to add catch the error and print a pretty message to the user that the file is not there. 

For now we will print it in the log, but in the long run we might want a loading screen for the users so they can see that Jenkins is currently being configured. We also need a way of configuring CasC

**Comment by buep** [comment]
YAML invalid?
