### ISSUE TITLE
Manage plugins installation/upgrade 

### ISSUE THREAD

**Issue by ewelinawilkosz2** [Praqma/configuration-as-code-plugin#21]
Plugins installation and update should be handled in a better way than it was in JenkisAsCodeReference - we can't expect people to generate list of installed plugins and maintain it manually every time they install something. 

- [ ] list of the plugins has to be maintained in an easy to read way (plugins.txt is not a bad example)
- [ ] If a new plugin is installed manually/updated/uninstalled the list of the plugin has to be updated
- [ ] Nice to have: option to install plugin without updating a list of plugins - kind of test installation (Once we have "reload configuration from file" it would be super easy to go back to previous plugin then)
- [ ] make sure dependencies are handled properly

**Comment by samrocketman** [comment]
> list of the plugins has to be maintained in an easy to read way (plugins.txt is not a bad example)

Here's a [Jenkins Script Console script][1].

```groovy
println Jenkins.instance.pluginManager.plugins.collect { "${it.shortName}:${it.version}" }.sort().join('\n')
```

[1]: https://wiki.jenkins.io/display/JENKINS/Jenkins+Script+Console

**Comment by ewelinawilkosz2** [comment]
comments from slack:
@kryptag we had an idea you could work on installing plugins issueI. 
have no real idea how to do that yet, but in general we want to have a list of the plugins we want to be installed somewhere in *.yaml file, could be plugins.yaml, just next to jenkins.yaml
and the real issue is to make sure that dependencies are being solved, so if you put there e.g. artifactory plugin it will install all the plugins artifactory depends on

**Comment by buep** [comment]
I elaborated the functionality and wrote two new issues based on a discussion in our team.

#44 replaces this issue.

#45 is more functionality to wish for later.
