### ISSUE TITLE
Create a branch with Nicolas prototype and continue development on that branch

### ISSUE THREAD

**Issue by ewelinawilkosz2** [Praqma/configuration-as-code-plugin#23]
code to copy: https://github.com/jenkinsci/configuration-as-code-plugin/tree/cloudbees
branchName: cloudbees

**Comment by buep** [comment]
Yes, we want to basically as the net result throw away our own code and replace it with the MVP using YML configuration approach without glue code.

For now we will pull in the cloudbees branch to this repo, and then later we will make that branch master and the existing master some old coco plugin branch.

**Comment by ewelinawilkosz2** [comment]
branch delivered, with some small changes to make it work without any additional setup (securityRealm switched to local)
