### ISSUE TITLE
Story: Review support of plugins installed by default

### ISSUE THREAD

**Issue by ewelinawilkosz** [Praqma/configuration-as-code-plugin#25]
when running the prototype with mvn hpi:run a number of plugins is being installed by default,
make a list and try to configure each on of the by the current version of the prototype
provide result about which plugins can be configured and which can't

**Comment by buep** [comment]
We're moving to the jenkinsci fork repo so going over things in this repo to see if we need anythings, closing issues etc.

and I made new issue in the other repo around this
