### ISSUE TITLE
Warning plugin support

### ISSUE THREAD

**Issue by buep** [Praqma/configuration-as-code-plugin#26]
We have decided the Warnings plugin should be supported in our MVP, so how difficult is to support it?

Can it be configured as the MVP is now with YML?

In case it can not be supported, we need to look into why this is the case what how this can be fixed.
If it is supported, we want to write a test that is easy tor read and use as documentation on that is supported.

**Timebox work 4 hours** - please add working notes along the way on this issue for all things you do and learn during those 4 hours.  Please add a comment to all things related to the following bullets.

Proposal for how to get started:

* `mvn hpi:run` get your developer debug Jenkins running.
* Install the warnings plugin
* check the java doc autogenerated by configuration as code plugin, and see if warnings plugin have a footprint there ?
* check the global configuration the plugin have, and see what the fields are called 
* try to configure the YML for the plugin see if you can get information in there

If it doesn't work after few tries, we may conclude is it not directly useable or user-friendly, and we should clone the warnings plugin repository and look at what is missing for the automated support. Make a list of finding along the way.

**Comment by buep** [comment]
Any findings to share? For example how the plugin is going to be installed using mvh hpi:run?
Did Warnings give java doc entries when installed?
Which fields are available for us to configure?

**Comment by groenborg** [comment]
installing the warnings plugin did not add anything to the documentation. I tried upgrading to Jenkins 2.60.1 because most of the plugins did not support the older version `2.60`. IT did add 
- GlobalMatrixAuthorizationStrategy
- ProjectMatrixAuthorizationStrategy

to the config file. I am trying to take a tutorial on Jenkins plugin development to figure out what is Jenkins specific and best practice

**Comment by buep** [comment]
## Installing plugins

When I do `mvn hpi:run` there are basically no plugins installed.

I can see from this [pom.xml ](https://github.com/Praqma/configuration-as-code-plugin/blob/1ae35cd1d77ee916f32ff6b21392efc482069e34/pom.xml) that there is a dependency on ldap for demo purpose as the comment says.
The ldap plugin is also installed.

But adding Warnings the same fails with and error of Maven being able to resolve the dependency.

```
...

    <!-- for demo purpose -->
    <dependency>
      <groupId>org.jenkins-ci.plugins</groupId>
      <artifactId>ldap</artifactId>
      <version>1.16</version>
      <type>hpi</type>
    </dependency>

    <dependency>
      <groupId>org.jenkins-ci.plugins</groupId>
      <artifactId>warnings</artifactId>
      <version>LATEST</version>
      <type>hpi</type>
    </dependency>
  </dependencies>
```

Error:
```
[INFO] Scanning for projects...
[WARNING] The POM for org.jenkins-ci.tools:maven-hpi-plugin:jar:1.117 is missing, no dependency information available
[WARNING] Failed to build parent project for org.jenkins-ci.plugins:configuration-as-code:hpi:1.0-SNAPSHOT
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] Building Configuration as Code Plugin 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] >>> maven-hpi-plugin:1.117:run (default-cli) > compile @ configuration-as-code >>>
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2.969 s
[INFO] Finished at: 2017-10-25T20:29:43+02:00
[INFO] Final Memory: 23M/345M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project configuration-as-code: Could not resolve dependencies for project org.jenkins-ci.plugins:configuration-as-code:hpi:1.0-SNAPSHOT: Failed to collect dependencies at org.jenkins-ci.plugins:warnings:hpi:LATEST: Failed to read artifact descriptor for org.jenkins-ci.plugins:warnings:hpi:LATEST: Failed to resolve version for org.jenkins-ci.plugins:warnings:hpi:LATEST: Could not find metadata org.jenkins-ci.plugins:warnings/maven-metadata.xml in local ....
```

But the Artifactory plugin works, and downloads a lot of dependencies and Jenkins comes up with that plugin installed.

Dependencies section in `pom.xml` would then look like this:

```
  <dependencies>
    <dependency>
      <groupId>org.yaml</groupId>
      <artifactId>snakeyaml</artifactId>
      <version>1.18</version>
    </dependency>


    <!-- for demo purpose -->
    <dependency>
      <groupId>org.jenkins-ci.plugins</groupId>
      <artifactId>ldap</artifactId>
      <version>1.16</version>
      <type>hpi</type>
    </dependency>

    <dependency>
      <groupId>org.jenkins-ci.plugins</groupId>
      <artifactId>artifactory</artifactId>
      <version>LATEST</version>
      <type>hpi</type>
    </dependency>
  </dependencies>
```

Might have been newbie knowledge, but why didn't Warnings not just work out of the box?

The Artifactory plugin pulled in a lot of other plugins. This makes sense if we look at their [`pom.xml`](https://github.com/jenkinsci/artifactory-plugin/blob/master/pom.xml) which have those as dependencies. 

**So there are some knowledge in our team we need to learn around dependencies in between plugin**.
This might be a good place to start: https://wiki.jenkins.io/display/JENKINS/Dependencies+among+plugins


So in sense of this issue, I doesn't make sense to explore the Warnings plugin further with the described steps, since we can't install, thus not run the javadocs etc.
Will continue the exact same work on #27 which is about the artifactory plugin.

The commit shared on this issue is probably not relevant - it just shows the Warnings plugin as dependency which doesnt work.
