### ISSUE TITLE
Mailer plugin support investigation

### ISSUE THREAD

**Issue by ewelinawilkosz** [Praqma/configuration-as-code-plugin#28]
It seems Mailer plugin is not supported out of the box by the prototype
It was mentioned by CB that some plugins will require glue code and that might be the case, further investigation needed

As a result of that issue we need to have a way to configure Mailer - that's very basic functionality for Jenkins

**Comment by buep** [comment]
@groenborg had some findings I believe around this so it might be quite easy to make it work. If so, can you estimate this issue @groenborg

**Comment by groenborg** [comment]
The mailer plugin needed a getDescriptor which I tried to implement, however that did not work. So right now we are waiting for feedback on monday and on issue #51 
So we cannot estimate this now.

**Comment by buep** [comment]
**This issue not relevant anymore**


We're moving to the jenkinsci fork repo so going over things in this repo to see if we need anythings, closing issues etc.
