### ISSUE TITLE
Implement support for Matrix Based Security

### ISSUE THREAD

**Issue by alexsedova** [Praqma/configuration-as-code-plugin#3]
Implement the same logic like  https://github.com/Praqma/JenkinsAsCodeReference (dockerizeit/master/matrixbasedsecurity.groovy) in java

**Comment by ewelinawilkosz2** [comment]
Use Nicolas prototype and try to see if it is working out of the box or implement fixes?
Provide tests

**Comment by groenborg** [comment]
https://github.com/Praqma/configuration-as-code-plugin/issues/26

**Comment by groenborg** [comment]
list of extension points
https://jenkins.io/doc/developer/extensions/

**Comment by alexsedova** [comment]
Spent a day for investigation. 
matrix-auth plugin has two strategies we configuring at the global configuration block: GlobalMatrixAuthorisationStrategy and ProjectMatrixAuthorisationStrategy. GlobalMatrixAuthorisationStrategy extends AuthorisationStrategy extension point. So follow the logic I got from all (not so fully represented I would say) information about Extension points, annotations, data bounded constructors and so on, I used authorizationStrategy bounded variable as an entry point to the configuration in jenkins.yaml, after that I pointed the type of the strategy which is  GlobalMatrixAuthorisationStrategy, and after that I found a trouble. I should present for GlobalMatrixAuthorisationStrategy a list of permissions granted for different users/groups. I followed the easiest way (took a look at the config.xml) and listed - permission: <permission:user> But Jenkins fault with "GlobalMatrixAuthorisationStrategy does not have @DataBoundConstructor". And there is my list of questions:
- Should we always have @DataBoundConstructor in such a cases?  I saw this question in one of the issues threads. @groenborg @buep @kryptag if you guys already have a clear understanding how we should proceed in such cases please share) maybe we organize kind of sharing knowledge session? 
- Having DataBoundConstructor  is a obligatory circumstance? Is there any way/workaround how we can fix this. 
I'm going to play around with a local version the matrix plugin, but would be nice to have some advises)
I would be really appreciated any knowlinge sharing or advises since I stacked with this issue.
@ewelinawilkosz2 @buep  Maybe take it out from mvp for now? I'm sorry to say but If there is no quick answer/fix for my question I don't see how it will be done till next week((

**Comment by buep** [comment]
Can you share the code so we're looking at the same? issue3 branch was old.

Else I would we put the above finding our question list - thanks for summarizing it, so we can continue with it.

**Comment by alexsedova** [comment]
@buep There is no real code to share I would say, I just played with different types of bounded variables I found in the plugin code and your, guys, commits. So the snippet in jenkins.yaml file I failed is: 
```authorizationStrategy:
        GlobalMatrixAuthorizationStrategy:
            - permission: hudson.model.Hudson.Administer:authenticated
```

**Comment by buep** [comment]
We're moving to the jenkinsci fork repo so going over things in this repo to see if we need anythings, closing issues etc.

This issue not relevant anymore.
