### ISSUE TITLE
Story: Location of configuration file has to configurable

### ISSUE THREAD

**Issue by ewelinawilkosz** [Praqma/configuration-as-code-plugin#31]
There should be a default location that the plugin will look into but if there is e.g. environment variable set up that points to another location or git repository (or some other storage solution, has to be further discussed) it should use this location and act accordingly - read the file, pull it from repo etc

**Comment by ewelinawilkosz2** [comment]
default location can't stay the way it is now - it searches in plugin repository and that won't be available when the plugin is being installed on working Jenkins. I think somewhere in $JENKINS_HOME could be a good default location, like $JENKINS_HOME/jenkins.yaml, but we can discuss if there are other opinions. 

JENKINS_CONF should be the name of the variable we'll use and it can store:
* path
* github url
* [what else?]

It should recognise type of the storage and act accordingly - read the file from filesystem, clone the repo somewhere in Jenkins workspace and read the file then - or can it be read directly from e.g. github?

**Comment by buep** [comment]
I think this issue is to big, so let's make it a briefing - like a story kind of - with room for discussion. 

I'll write a new  issues for supporting configuration through github.

**Comment by buep** [comment]
#47 is first step at supporting configuration file locations.

**Comment by buep** [comment]
We're moving to the jenkinsci fork repo so going over things in this repo to see if we need anythings, closing issues etc.
