### ISSUE TITLE
add .gitconfig for our workflow

### ISSUE THREAD

**Issue by groenborg** [Praqma/configuration-as-code-plugin#35]

**Comment by ewelinawilkosz2** [comment]
isn't it .phlow file we have to add?

**Comment by ewelinawilkosz2** [comment]
apparently it is not enough :) or it's not that at all, anyway, I need instruction on how to make cloudbees the integration branch, can't use git phlow without it :(

**Comment by groenborg** [comment]
it is not the .phlow file, it is the .gitconfig file.. However with the new version, we use the base config so adding the .gitconfig is not necessary.

**Comment by groenborg** [comment]
I will close this issue since it is not relevant after @ewelinawilkosz2 changes the master branch :)
