### ISSUE TITLE
Explore Warnings plugin configuration

### ISSUE THREAD

**Issue by ewelinawilkosz2** [Praqma/configuration-as-code-plugin#37]
Use findings from #34 

Questions to answer: 

Are all the plugins extension point available from the core or do we have to make plugin look for them somewhere else, like plugin manager?

How to get Warnings plugins recognisable and configurable by the plugin?

As a result we want to either have the Warnings plugin configure or conclusion about what is missing to make it possible - in that case new issue has to be created

**Comment by groenborg** [comment]
I think it needs the static class which implements the descriptor and overrides configure and getDescription

https://github.com/jenkinsci/warnings-plugin/blob/master/src/main/java/hudson/plugins/warnings/WarningsDescriptor.java

**Comment by groenborg** [comment]
I am unsure about the jelly stuff.. Still looking into that

**Comment by groenborg** [comment]
Could not build any of the plugins I cloned from Jenkinsci, they failed with exceptions: 
```
java.nio.file.NoSuchFileException on stabler.Extension and java.io.EOFException when tring to build Jenkins Plugin from source. 
```
the solution: https://stackoverflow.com/questions/32127424/java-nio-file-nosuchfileexception-and-java-io-eofexception-when-tring-to-build-j 

They do not work with Jdk 9 use jdk 8

**Comment by buep** [comment]
Right, was it Warnings plugin and just latest master commit?

You need to adjust your developer environment, or use a mvn container

**Comment by groenborg** [comment]
https://github.com/jenkinsci/mailer-plugin/tree/18b8274e1a31b60d7e20492f1ecfa39483b90b37 

Set it to jdk8

**Comment by groenborg** [comment]
I get this whenever I try to view the docs now, nothing have changed.. It is a clean slate: Stapler processed this HTTP request as follows, but couldn't find the resource to consume the request

-> evaluate(<hudson.model.Hudson@7de40301> :hudson.model.Hudson,"/configuration-as-code")
-> evaluate(((StaplerProxy)<hudson.model.Hudson@7de40301>).getTarget(),"/configuration-as-code")
-> evaluate(<hudson.model.Hudson@7de40301>.getDynamic("configuration-as-code",...),"")
            hudson.model.Hudson@7de40301.getDynamic("configuration-as-code",...)==null. Back tracking.
-> evaluate(((StaplerFallback)<hudson.model.Hudson@7de40301>).getStaplerFallback(),"/configuration-as-code")
-> evaluate(<hudson.model.AllView@1b08be69[view/all/]> :hudson.model.AllView,"/configuration-as-code")
-> evaluate(<hudson.model.AllView@1b08be69[view/all/]>.getDynamic("configuration-as-code",...),"")
            hudson.model.AllView@1b08be69[view/all/].getDynamic("configuration-as-code",...)==null. Back tracking.
-> No matching rule was found on <hudson.model.AllView@1b08be69[view/all/]> for "/configuration-as-code"

**Comment by buep** [comment]
can you share the commit?

**Comment by groenborg** [comment]
I have added nothing, just clone the repository

**Comment by buep** [comment]
so if i clone our configuration-as-code repository and do mvn hpi:run I get to see the same problem?

**Comment by groenborg** [comment]
Chances are that you will, however nothing have been added since last time it worked. So I am led to believe that something in my setup is still given me problems. But please spin it up and see what you get.

**Comment by buep** [comment]
Oh I see, your Jenkins runs just fine... it is the docs url that is broken visiting http://localhost:8080/jenkins/plugin/configuration-as-code/ I get this:

```
404 Not Found

Stapler processed this HTTP request as follows, but couldn't find the resource to consume the request

-> evaluate(<hudson.model.Hudson@453a5ccf> :hudson.model.Hudson,"/plugin/configuration-as-code")
-> evaluate(((StaplerProxy)<hudson.model.Hudson@453a5ccf>).getTarget(),"/plugin/configuration-as-code")
-> evaluate(<hudson.model.Hudson@453a5ccf>.getPlugin("configuration-as-code"),"")
-> unexpected null!

If this 404 is unexpected, double check the last part of the trace to see if it should have evaluated to null. 
```


But also jenkins have a lot of unresolved dependencies. 
![selection_216](https://user-images.githubusercontent.com/1579826/32232400-3d63cee0-be58-11e7-8de5-12ccde7ec245.png)

**Comment by buep** [comment]
Here is how to make it work:

1. git clone repo
1. cd repo
1. mvh hpi:run
1. get token from terminal to continue to spin up Jenkins
1. chose recommended pluigns to be installed - many of these will fail, because I think we install never ones
1. create user
1. login 

your up and running and docs url works as well: http://localhost:8080/jenkins/plugin/configuration-as-code/

**Comment by buep** [comment]
instead of clone, you can do `rm -rf work` and `git checkout master && git pull`

I used https://github.com/Praqma/configuration-as-code-plugin/commit/b4544a4ea1d65069c3c73500835cc9b2d1f6e721

**Comment by groenborg** [comment]
That is the process.. Still does not work!

**Comment by buep** [comment]
how does your mvn environment look like?

```
^bue@orange-two:~/github-repos/praqma/casc-tmp$ mvn --version
Apache Maven 3.5.0 (ff8f5e7444045639af65f6095c62210b5713f426; 2017-04-03T21:39:06+02:00)
Maven home: /usr/local/apache-maven-3.5.0
Java version: 1.8.0_131, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-8-openjdk-amd64/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "4.10.0-37-generic", arch: "amd64", family: "unix"
bue@orange-two:~/github-repos/praqma/casc-tmp$ 
```

**Comment by groenborg** [comment]
I made the documentation work again by deleting the repo and restart my computer and clone it again. The changes I made to the warnings plugin, did not work. I followed this guide: http://code.hootsuite.com/how-to-write-a-jenkins-plugin/ but it does not seem to meet the requirements of the current plugin. I will close the issue for now and create a new one after our meeting with cloudbees
