### ISSUE TITLE
Load Jenkins configuration file from github repository URL

### ISSUE THREAD

**Issue by buep** [Praqma/configuration-as-code-plugin#47]
As a part of implementing our story in #31 where we want to be able to give configuration to the plugin from different location, we want to support git repository from an url as the first thing.

Please start by reading #31 to get the context.

The current `jenkins.yml` should be read from a git url in a fully qualified way, meaning I'll pass the complate path to a specific version of the file... 

Such an url could look like this: 

* https://github.com/Praqma/configuration-as-code-plugin/blob/master/jenkins.yaml which would then be just master and a floating version if users prefer latest
* https://github.com/Praqma/configuration-as-code-plugin/blob/b4544a4ea1d65069c3c73500835cc9b2d1f6e721/jenkins.yaml for a very specific version.

From those urls I believe you can get the RAW content.

We would like the plugin to get the git url from an environment variable available at runtime called `JENKINS_CONF`.

The context of that is we will be passing this into a container with the Jenkins master we deploy this.

**Comment by ewelinawilkosz2** [comment]
I like the idea of passing specific version - although it doesn't make a difference for the implementation, right? 

getting raw seems to be pretty easy, just replace 'blob' with 'raw' and you get new links:
- https://raw.githubusercontent.com/Praqma/configuration-as-code-plugin/master/jenkins.yaml
- https://raw.githubusercontent.com/Praqma/configuration-as-code-plugin/b4544a4ea1d65069c3c73500835cc9b2d1f6e721/jenkins.yaml

what we have to consider is authentication - in most cases I imagine the configuration will be kept in some private repos so we need to provide a way to authenticate/authorize the request, any ideas?

And @buep you mention passing it to a container - you mean the`JENKINS_CONF` variable? or the file? remember it also has to work in docker free env.

Anything else not clear in this issue?

**Comment by buep** [comment]
> you mean theJENKINS_CONF variable
Yes.

Good point about authentication.... propose to handle that later, as it will probably be the same way we need to handle authentication on Jenkins towards for example Github anyway.

**Comment by groenborg** [comment]
related to #53

**Comment by buep** [comment]
@groenborg @kryptag this issue I would like to see implemented soon - what is your timebox?

**Comment by buep** [comment]
Smalll timebox to only support github, few lines of code change. No auth at the moment.

**Comment by buep** [comment]
For the demo purpose, we don't have to create a specific repository for one `jenkins.yml` file, we can re-use this repository. 

So goal is to be able to load the jenkins configuration from this url: https://github.com/Praqma/configuration-as-code-plugin/blob/master/jenkins.yaml

**Comment by kryptag** [comment]
we have decided that it doesn't make sense to make string manipulation and try to track which service the file comes from as long as it points to a valid `yaml` file. We wont think about authentication for the moment, this is mentioned in #56.

**Comment by kryptag** [comment]
it now works with environment variable `JENKINS_CONF` it a rather ugly solution but it will suffice for now, its very important that you use `https://raw.githubusercontent.com/Praqma/configuration-as-code-plugin/master/jenkins.yaml` the raw version because it tested with this.

**Comment by ewelinawilkosz2** [comment]
do we check if the variable is set? I guess it's pretty easy and when I looked at the code I haven't seen that. but maybe I missed that :) so @kryptag please comment before we decide if we need an issue on that

**Comment by buep** [comment]
created issue for you
