### ISSUE TITLE
Add version support for plugins

### ISSUE THREAD

**Issue by kryptag** [Praqma/configuration-as-code-plugin#49]
Read issue #44. This issue is dependant on #48 being fixed first

*Goal*: make sure the version mentioned in the `plugin.yml` file used when installing plugin. The version should be part of the YML file so each plugin can mention a specific version.

**Comment by buep** [comment]
We're completely deleting this repo.
We're moving to the jenkinsci fork repo so going over things in this repo to see if we need anythings, closing issues etc.

there is a relevant issue to handle this in the jenkinsci repo
