### ISSUE TITLE
Add credentials support

### ISSUE THREAD

**Issue by ewelinawilkosz** [Praqma/configuration-as-code-plugin#5]
current way of maintaining credentials isn't very pretty nor efficient - the need to create a file and put in a secure location on a remote machine... or somewhere when docker can reach it - don't have a better idea yet, so it requires some brain storming! @praqma-thi @MadsBaggesen wanna join the storm??

**Comment by buep** [comment]
We're moving to the jenkinsci fork repo so going over things in this repo to see if we need anythings, closing issues etc.

This issue not relevant anymore.
