### ISSUE TITLE
plugin requirements for casc

### ISSUE THREAD

**Issue by groenborg** [Praqma/configuration-as-code-plugin#51]
We would like to accumulate a list of all (or most essential) the plugins that are supported, and the requirements the plugin needs to fulfill in order to work with casc. We have tried to get the Mailer plugin up and running #37, but concluded that it did not work after we made our own changes. So being able to see what is missing for a plugin to work would be very valuable.
- Should it have a `@DataboundConstructor` 
- What extension points are supported in Jenkins?  
- Should the nested Descriptor class have the `@Extension` annotation 
- Should we have a nested `static class DescriptorImpl` 
- What can be extended (Plugin)
- What is a no go to get a plugin up and running

The list above are all of our unknowns which we need to answer

**Comment by buep** [comment]
The background for this issues is when we demonstrate the configuration as code project to our customers, we want to also answer them how much time it will take to support their list of used plugins.
Some of them might be supported out of the box, some needs glue code (**temporarily**) while we get PR's through to the plugin themselves.

To be able to come up with estimates for our customers, we would need to know exactly what to look for in those plugins. 

So a checklist to go through and maybe information on how to easily try it would be a good help.

**Comment by buep** [comment]
**This issue not relevant anymore**


We're moving to the jenkinsci fork repo so going over things in this repo to see if we need anythings, closing issues etc.
