### ISSUE TITLE
Create image for casc container

### ISSUE THREAD

**Issue by groenborg** [Praqma/configuration-as-code-plugin#52]
as a part of the JCasC container we need the docker image as code, and will create a Dockerfile based off the official Jenkins LTS release and add the JCasC hpi.

**Comment by buep** [comment]
Dockerfile based on Jenkins LTS with support for taking env var JENKINS_CONF in and to copy in build hpi file. See #54

**Comment by groenborg** [comment]
The docker image from Jenkins:lts does not  have Jenkins installed (should have realized that), it spins up the installation wizard. We need to skip the installation wizard and let the plugin do that, however the basic file structure should be there so our plugin is available for Jenkins. I could understand from @ewelinawilkosz2 that this line in the old project should skip the installation wizard. https://github.com/Praqma/JenkinsAsCodeReference/blob/7005ca6c2f2a8fcc410cdba804b728637f4c6068/dockerizeit/master/Dockerfile#L10
