### ISSUE TITLE
JCasC configuration though env-var

### ISSUE THREAD

**Issue by groenborg** [Praqma/configuration-as-code-plugin#53]
CasC needs to be able to pull a configuration file from a GitHub repo. To do this in a container we will pass the uri to file though a variable passed to the contianer, which will be exposed as an env-variable casc can use.

**Comment by buep** [comment]
How is this different than #47 or not included in #52 ?

**Comment by buep** [comment]
Covered trivially by #52 when creating the Dockefile and by #47 when supporting the environment variable.
