### ISSUE TITLE
Handle github authentication when using external repo to store conf file

### ISSUE THREAD

**Issue by ewelinawilkosz** [Praqma/configuration-as-code-plugin#56]
in #47 we provide a way to get a configuration file from github repository, it may happen the repository will be private and we need to handle authentication so our plugin can access the file

**Comment by groenborg** [comment]
Github and other repos uses either OAuth or support basic token authentication, so this is is just a matter of submitting a username and and token as an env-variable together with the uri. This should not be difficult. We have done the same thing with git-phlow.

**Comment by buep** [comment]
Doesn't sound safe for me... passing secrets using env variables... so there must be other ways.
What about using some of the mechanism Jenkins already have? Remember this is running from within Jenkins.

**Comment by buep** [comment]
Made it a briefing... since we're not clear on what we want.

**Comment by groenborg** [comment]
Alright, no matter how we handle the credentials, Auth should not be a problem

**Comment by buep** [comment]
We're completely deleting this repo.
We're moving to the jenkinsci fork repo so going over things in this repo to see if we need anythings, closing issues etc.
