### ISSUE TITLE
If JENKINS_CONF env var is not set or empty we should report an error

### ISSUE THREAD

**Issue by buep** [Praqma/configuration-as-code-plugin#57]
Related to #47 comment https://github.com/Praqma/configuration-as-code-plugin/issues/47#issuecomment-341638772 please handle error related to `JENKINS_CONF` variable not set or empty.

**Comment by kryptag** [comment]
where do you want the error to be reported ?

**Comment by kryptag** [comment]
i will add error handling that prints out the error and message to the console and remove redundant code for Jenkins_conf and Jenkins_plugins

**Comment by kryptag** [comment]
We should look into moving some of the error messaging to the UI so if you use this on a running instance you get the feedback without looking into the logs, but i guess for now this should suffice
