### ISSUE TITLE
Provide a way to generate conf. file from existing Jenkins

### ISSUE THREAD

**Issue by ewelinawilkosz** [Praqma/configuration-as-code-plugin#6]
conf files will be used to store complete Jenkins and plugins configuration. In case someone wants to migrate from traditional Jenkins to AsCode solution and use the plugin we should provide a way to export configuration of existing simple as a ready to use conf files

**Comment by buep** [comment]
**This issue present in new form in new repo.**


We're moving to the jenkinsci fork repo so going over things in this repo to see if we need anythings, closing issues etc.
