### ISSUE TITLE
Story: End user feedback

### ISSUE THREAD

**Issue by buep** [Praqma/configuration-as-code-plugin#62]
Reporting to end-user needs to be improved.

For example when YAML isn't valid or can't be used somehow in Jenkins configuration

Detect the user is trying to configure something, and that it doesn't work. Point to examples.

**Comment by ewelinawilkosz2** [comment]
- #69 
- #70

**Comment by buep** [comment]
created related new issue in jenkinsci

We're moving to the jenkinsci fork repo so going over things in this repo to see if we need anythings, closing issues etc.
