### ISSUE TITLE
Finish the JEP document... create PR the official repo

### ISSUE THREAD

**Issue by buep** [Praqma/configuration-as-code-plugin#63]
convert it to markdown...

**Comment by ewelinawilkosz2** [comment]
https://github.com/jenkinsci/jep is the official repo - have a look at formatting there and create our own, on a branch, based on: https://docs.google.com/document/d/1lx_caE3MIH4kkCjz3KQpN2QB31c1_b50JvSoyjiAqDU/edit?usp=sharing
review internally before pushing, @buep mentioned we may want more user stories - coordinate with him (unless Bue is the one taking this ticket)

**Comment by groenborg** [comment]
Is this basically just taking the jep document and convert it to markdown?

**Comment by ewelinawilkosz2** [comment]
we'll wait with that one for now, from slack:

> the supposed  process is to first discuss this on mailing list, then write a proposed JEP, then if approved create a PR on jep repository

**Comment by buep** [comment]
We're moving to the jenkinsci fork repo so going over things in this repo to see if we need anythings, closing issues etc.
