### ISSUE TITLE
Copy latest changes pushed by Nicolas

### ISSUE THREAD

**Issue by ewelinawilkosz2** [Praqma/configuration-as-code-plugin#66]
Nicolas pushed some changes yesterday: https://github.com/jenkinsci/configuration-as-code-plugin/commit/6a694381e28114a7103682f06eb1134880e50fff we need to move those to our repo (unless we decide to move the implementation to jenkinsci, we'll discuss during daily meeting)

**Comment by groenborg** [comment]
Our master ranch seems to have been moved or started from scratch at some point in the git history, so there is no longer any shared history between the two repositories. I can try to do a merge with `unrelated-history` and solve the conflicts

**Comment by groenborg** [comment]
I have merged the changes into our repository, but not pushed them back to Jenkinsci, is that something we want do now?

**Comment by groenborg** [comment]
done in 0c9b1265a12ae1c2888761bbcb6eb56ba6fbae8b
