### ISSUE TITLE
Printout in terminal if configuration is not supported

### ISSUE THREAD

**Issue by ewelinawilkosz** [Praqma/configuration-as-code-plugin#69]
When user tries to configure something that is not supported yet - so there is a valid yaml but e.g. Mailer configuration is ignored - the user has to be informed, that this specific part of yaml file was skipped

for now inly printout in terminal, once we implement UI we will have a new issues to display it there

**Comment by buep** [comment]
There are some schema validation now available.. so not relevant anymore.

We're moving to the jenkinsci fork repo so going over things in this repo to see if we need anythings, closing issues etc.
