### ISSUE TITLE
Provide a way to hot reload/reconfigure without restart 

### ISSUE THREAD

**Issue by ewelinawilkosz** [Praqma/configuration-as-code-plugin#7]
if a user doesn't want/can't restart Jenkins and want to introduce a change in configuration via updates in conf files we need a simple way to allow that - reloading/reconfiguring without the actual restart (currently the conf files are being read when starting/restarting Jenkins)

We need:
- [ ] 'Reload configuration' button
- [ ] API endpoint
- [ ] Pipeline function (?)

**Comment by buep** [comment]
**This issue present in new form in new repo.**


We're moving to the jenkinsci fork repo so going over things in this repo to see if we need anythings, closing issues etc.
