### ISSUE TITLE
Handle yaml not present or not valid

### ISSUE THREAD

**Issue by ewelinawilkosz** [Praqma/configuration-as-code-plugin#70]
it may be already implemented but has to be confirmed, what happens when:

1. JENKINS_CONF or JENKINS_PLUGINS variables are not set
2. JENKINS_CONF or JENKINS_PLUGINS link file that doesn't exist
3. yaml is not valid

If any of those cases is not properly handled (properly handled means there is an output in terminal that's understandable for the user) create an issue to fix it

**Comment by buep** [comment]
**This issue present in new form in new repo.**


We're moving to the jenkinsci fork repo so going over things in this repo to see if we need anythings, closing issues etc.
