### ISSUE TITLE
Verify plugins compatibility with new version of prototype we merged from jenkisci

### ISSUE THREAD

**Issue by ewelinawilkosz** [Praqma/configuration-as-code-plugin#71]
We have a list of plugins we tested documented by @groenborg , after Nicolas introduced some changes the list has to be updated

**Comment by ewelinawilkosz2** [comment]
@groenborg couldn't finish #72 but it still has to be updated

**Comment by buep** [comment]
**This issue not relevant anymore**


We're moving to the jenkinsci fork repo so going over things in this repo to see if we need anythings, closing issues etc.
