### ISSUE TITLE
update documentation matrix

### ISSUE THREAD

**Issue by groenborg** [Praqma/configuration-as-code-plugin#72]
Update the compatibility matrix to a three column design with | plugin | Global | other | and update which plugins work and does not work

**Comment by ewelinawilkosz2** [comment]
just make sure:
- you include yaml you tried for not working plugins also
- whenever the piece of configuration is not root element but has parent make sure to include parents in the piece of code you provide

**Comment by groenborg** [comment]
I have not been able to generate the docs and thereby investigate what plugin works and what does not. Every time I run Jenkins and try to access the docs I get: 
```
Problem accessing /jenkins/plugin/configuration-as-code/. Reason:

    Not Found
```
