### ISSUE TITLE
Dynamic Load

### ISSUE THREAD

**Issue by groenborg** [Praqma/configuration-as-code-plugin#73]
Some plugins can not be dynamically loaded, which means that we have to restart Jenkins for the plugins to be installed. This introduces a manual step in the setup process. 

how do we handle this? do we need to force plugins to work with dynamic load?

**Comment by groenborg** [comment]
```
INFO: Attempting to dynamic load /Users/simon/GitHub/praqma/configuration-as-code-plugin/work/plugins/maven-plugin.jpi
nov. 09, 2017 1:02:29 PM hudson.model.UpdateCenter$DownloadJob run
SEVERE: Failed to install Maven Integration plugin
java.io.IOException: Failed to dynamically deploy this plugin
```

**Comment by buep** [comment]
**This issue not relevant anymore**


We're moving to the jenkinsci fork repo so going over things in this repo to see if we need anythings, closing issues etc.
