### ISSUE TITLE
Review new version of prototype

### ISSUE THREAD

**Issue by ewelinawilkosz** [Praqma/configuration-as-code-plugin#74]
read discussions at:

- https://github.com/jenkinsci/jep/pull/31/files/a50d360be828dbbeb5d425cf01c51913eeffebcc#r149643508
- https://groups.google.com/forum/#!topic/jenkinsci-dev/MuRJ-yPRRoo

Prepare questions before the meeting at 2pm, 10.11.17

**Comment by buep** [comment]
**This issue not relevant anymore**


We're moving to the jenkinsci fork repo so going over things in this repo to see if we need anythings, closing issues etc.
