### ISSUE TITLE
Find a solution for a case when there is conf. file but no plugin installed 

### ISSUE THREAD

**Issue by ewelinawilkosz** [Praqma/configuration-as-code-plugin#9]
After short discussion:

- If in docker then it is better to handle plugins installation during image build
- If not in docker then there is no other good way to handle that and we should give a hand to user
Provide possibility to configure such behavior where plugins are installed automatically when conf. file exists

**Comment by buep** [comment]
If a user tries to configure Jenkins using configuration for a plugin that is not installed, we should issue an warning.

**Comment by buep** [comment]
We're moving to the jenkinsci fork repo so going over things in this repo to see if we need anythings, closing issues etc.
